server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: h2
  application:
    name: battery-platform-backend
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.battery.platform.entity

logging:
  level:
    com.battery.platform.mapper: debug
